CREATE DATABASE IF NOT EXISTS instagram_clone CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE instagram_clone;
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
